### ISSUE TITLE
Benches around Bath don't have images

### ISSUE THREAD

**Issue by danielthepope** [edent/openbenches#103]
https://openbenches.org/#51.38067/-2.355537/13, e.g. https://openbenches.org/bench/107/

There don't seem to be any images associated with the benches in this area. I noticed they're quite early entries.

**Comment by edent** [comment]
Yup - we got them from https://github.com/BathHacked/banes-geographic-data/blob/master/banes_park_seats_and_benches.geojson?

There were no photos in that dataset.

The plan is to have an "Add Image" button at some point :-)

**Comment by danielthepope** [comment]
Ah, good ol' Bath Hacked, I should have known :P

**Comment by edent** [comment]
We now have an Edit button - so people can add images.
