### ISSUE TITLE
Original images including all EXIF data are available.

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#104]
I was surprised to discover OpenBenches makes the original images people uploaded complete with all the EXIF data. I think this needs to either not be the case (ongoing and retrospectively), or clearly and explicitly stated at the top of https://openbenches.org/add/

Possibly "This means other people can use the photo and its data" is supposed to convey this situation, but if it is intended to do that I don't think it does so sufficiently. "its data" is open to interpretation. It could easily be interpreted as "the data which I am consciously giving you", which is the location and inscription. Also it's at the bottom of the page, beneath the Share button, in relatively small text.

Two of the photos available on the site at time of writing contain serial numbers labelled as such. For one of those serial numbers I was quite quickly able to find other photos taken by the same device and they have a person's name associated with them. Given the number of photos they've posted online over the years, I'd guess this person would be OK with my having worked out they took a photo of a bench at a certain date/time/place several years ago. Someone else may not be OK with such a link being made.

Of course many people don't know what EXIF is, probably even some of those uploading to a site which tells you that you must have GPS information included in the photo. Maybe their friend just told them to tap that option on the screen and that's as much as they thought about it. In some cases it seems to not be easily, if at all, discernable to the average person exactly what their device is putting in EXIF. (https://en.wikipedia.org/wiki/Exif#MakerNote_data)

Possible options:

- https://openbenches.org/add/ clearly states that the original image and all metadata will be made available to others and includes an explanation of what that means for those who have no idea what EXIF is.

- Original images are retained but not made available via the site.

- All but EXIF data except that essential to the concept of OpenBenches is removed from images when they are uploaded and from all images already uploaded. Essential data would be GPS, date, other? Time doesn't seem essential though removing that would be fiddly since it's stored in the same field as date.

**Comment by edent** [comment]
This is no different to how Flickr & Wikipedia stores & displays photos.

We mention this on http://www.openbenches.org/blog/privacy/ - including a link to what EXIF is.

The most personal information on those photos will be the location, which we specifically mention.  Device IDs are generally only on professional gear - so I assume those people will know what metadata they're including.

So, for now, we'll be keeping the metadata & serving it with the original photo. I'll make the privacy policy link more clear.

**Comment by arizonagroovejet** [comment]
The privacy page says "we record the following information". It does not say that information is made available via the website.
