### ISSUE TITLE
Search foiled by newlines and other whitespace

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#110]
The placeholder text https://openbenches.org/add/ encourages people to enter inscriptions with line breaks. The search function does not find inscriptions that contain line breaks if the words searched for are not all on the same line.

E.g.
https://openbenches.org/search/?search=This+Seat+Is+Dedicated+to+The+Cheshire+Regiment+Servicemen
returns no results, but it ought to return
https://openbenches.org/bench/210/

Other whitespace also prevents desired results being returned. E.g.
https://openbenches.org/search/?search=In+memory+of+Paul+Willmott
returns no results but it ought to return 
https://openbenches.org/bench/254
It doesn't because the person who entered the inscription put two spaces between "of" and "Paul"
```
$ curl -s  "https://openbenches.org/data.json/?bench=254&format=raw" | jq ".features[].properties.popupContent"
"In memory of  Paul Willmott<br />\r\n26-12-1940 - 14-7-2002<br />\r\nWho spend many happy hours here"
```
(They've also entered "spend" instead of "spent".) There's currently seven other inscriptions with erroneous double spaces.

There aren't currently any inscriptions with tabs in.

**Comment by edent** [comment]
This can be fixed using the magic power of [REGEXP](https://dev.mysql.com/doc/refman/8.0/en/regexp.html)!

Lets replace any spaces with `[[:space:]]*`

So the search becomes:

    SELECT *  FROM `benches` WHERE `inscription` REGEXP 'of[[:space:]]*Paul[[:space:]]*Willmott'
