### ISSUE TITLE
Some benches lack inscription text

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#111]
While tinkering with the inscription text retrieved via the API, I noticed some benches which lack their inscription text.

Inscription for these is clearly legible.
https://openbenches.org/bench/634
https://openbenches.org/bench/635
https://openbenches.org/bench/636

For https://openbenches.org/bench/1457 I believe the inscription reads
```
"fair Quiet, have I found thee here" (MARVELL)
"a garden is a lovesome thing" (BROWN)
Given by Bobbe & Myles Wilder
Temecula, California 1996 40th Anniversary
```
The first line is from https://en.wikipedia.org/wiki/The_Garden_(poem) Logically the f should be uppercase and the q lowercase, but the Q is clearly upper and the f looks lowercase to me.

The second line is from http://www.bartleby.com/236/149.html

The discernable name is Myles Wilder who turns out to be well known enough to have a Wikipedia entry https://en.wikipedia.org/wiki/Myles_Wilder, which is how I got Bobbe. 40th is a bit of a guess. I'm pretty certain the year is 1996. The last word is definitely Anniversary so good chance that what comes immediately before that is a number and ordinal indicator. This article from 2010 http://variety.com/2010/scene/news/tv-writer-producer-myles-wilder-dies-1118018275/ says he'd been married 53 years. 2010-53=1957 1996-1957=39. 53 year anniversary could have been in 2009 making 54th sometime after he died in 2010. Commemorating 40th wedding Anniversary with a bench seems more likely than 39th.

**Comment by edent** [comment]
Brilliant, thanks!

We've now got an edit link on each bench, so I've fixed those. But if you spot any more - feel free to dive in :-)
