### ISSUE TITLE
Search results are dense block of text

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#125]
As mentioned in #122 search results are presented as quite a dense block of text which isn't very eye friendly. It would be even less eye friendly if the LIMIT value for returned results was raised. Also the locations are presented at the end of the inscription text in () but some inscriptions also contain () so there is no clear separation of inscription text from location.

Current
![openbenches_search_current](https://user-images.githubusercontent.com/29510692/30757493-d2491f8e-9fc6-11e7-8593-b80fded07a94.png)
Proposed alternative
![openbenches_search_proposed](https://user-images.githubusercontent.com/29510692/30757502-ddb90bc2-9fc6-11e7-9370-0a3f278ce0bd.png)
The location is labelled as such to make it clear that this is a separate piece of information, but no label on the inscription because that's the thing people are expecting to get back from the search.

**Comment by edent** [comment]
Looks good! Do it!
