### ISSUE TITLE
load-image.all.min.js missing

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#127]
Tried adding a bench on a local instance of the website. I added a photo and it didn't get displayed in the page. Web browser console says
```
ReferenceError: loadImage is not defined[Learn More]  add:137:8
	<anonymous> https://localhost/add/:137:8
```
add.php contains reference to libs/load-image/load-image.all.min.js but that's not in the repo.

**Comment by edent** [comment]
Now fixed.
