### ISSUE TITLE
data.json endpoint returns spuriously

### ISSUE THREAD

**Issue by puntofisso** [edent/openbenches#139]
Is there a reason why this call 
`https://openbenches.org/data.json/?latitude=51.234&longitude=-1.234`

returns a variable like
`var benches = {"type":"FeatureCollection","features":[{"id":1,"type":"Feature","geometry":{"type":"Point","coordinates": [...]`

rather than just the JSON?

**Comment by puntofisso** [comment]
Never mind, I've [just :P] read in the README that this is by choice and can get the raw version using format=raw. Soz.

**Comment by edent** [comment]
RTFM or GTFO ;-)

It was originally designed that way to work with the Leaflet / OpenStreetMap stuff. I'm not sure if it's the most useful way of doing it though.
