### ISSUE TITLE
Main map not showing all benches

### ISSUE THREAD

**Issue by ukmoose** [edent/openbenches#141]
I added two benches near the northside of the woolwich ferry on Saturday  (in Royal Victoria Gardens)
e.g. https://openbenches.org/bench/4175

As of Monday 11am GMT the map on the home page still doesn't include them.

**Comment by edent** [comment]
Ah! We now have more than 4,096 benches - so I need to up the limit at https://github.com/edent/openbenches/blob/master/www/mysql.php#L227

Thanks - will try to fix this weekend. Pull Requests welcome though :-)
