### ISSUE TITLE
OpenStreetMap accuracy and quality.

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#142]
I've noticed some issues with OpenStreetMap as used on the site which are hindrances to accurately specifying bench locations when accuracy of location data in the photo is such that manual adjustment is in order.  I wonder how many bench locations have been adjusted based on what can be see on one of the map views and made less accurate as a result.  Has any consideration had been given to using a different source of map data?

1] In some places there is significant discrepancy between where things are on the map views. A particularly bad example I've noticed is https://openbenches.org/bench/4462 The positions of the building the bench is in, the footpaths, and Paddock Lane to the south-east differ by maybe something like 20 meters between the map views. The bench is either inside a building or quite a way outside it depending on which view you look at. It's impossible to tell which, if either, view is closest to reality. On Google Maps there is no such discrepancy, although the footpaths aren't shown except in satellite imagery. https://goo.gl/maps/X5QkNZbZ73u

2] The OpenStreetMap satellite is amazing in that we have such imagery at all, but it's terrible when compared to Google or Apple Maps. The photo shows the bench is next to X, X is clearly defined on Google Maps but the same area on OpenStreetMap satellite imagery is pixel mush so X can't be used as a reference.

3] The OpenStreetMap satellite imagery is old. The photo shows the bench is next to X, but X isn't on the satellite imagery at all so can't be used as a reference. For example, the location of  https://openbenches.org/bench/4439 is all grass in the OpenStreetMap satellite imagery but the landscaping is visible on https://goo.gl/maps/NmgDHrPBVtE2

**Comment by edent** [comment]
As far as possible, we want this to use open source components.

The photos retain their original EXIF, so locations can be reconstructed if necessary.  Typically phone GPS is accurate to between 5-10m - so location is fuzzy at best.

If you spot an error with OSM, [you can edit it](https://wiki.openstreetmap.org/wiki/Beginners_Guide_1.3)

**Comment by arizonagroovejet** [comment]
Fair enough.
