### ISSUE TITLE
Automatically try text detection on photo upload.

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#143]
The text detection feature is awesome. In my experience it produces something perfect or close to so often that I very nearly always click "Detect Text" button to see what it does. How about making it happen automatically when the Geotagged Photo is uploaded?

Awesome as the text detection is, it inevitably sometimes returns garbage or nothing at all. I don't bother trying it for inscriptions that are carved in to a bench as I've found it never produces anything useful for them, which is understandable given how difficult they can be to read with eyes. Given that, maybe some tweaks to the way the results of text detection are presented would be beneficial if it was triggered automatically. If you've clicked the button you know you've triggered it and are watching for the results to appear, but if you didn't trigger it and you didn't see the "scanning for text" message and then you see an empty textarea, you might wonder if the text detection is still in progress.

**Comment by edent** [comment]
This is a great idea.  I was a bit hesitant to make it automatic, because I didn't want to burn through the free tier that it is using - but it seems to be holding up.
I agree that it needs a better "please wait" experience.  Very happy if you want to commit something.

**Comment by arizonagroovejet** [comment]
I just noticed the text on /add/ says
> Select a photo of the bench's inscription and we'll try to auto-detect the text.

Which implies that auto-detection of the text will happen automatically when someone uploads a photo. So that wouldn't need changing.

Is the free tier is up to 1000 units a month? https://cloud.google.com/vision/  If so, given the rate at which benches have been added so far it seems unlikely a limit of 1000 a month would be exceeded. I'd bet that most people hit the "Detect Text" button already. (Imagine 1000+ benches added a month though, eh? :) )
 
I don't think very much needs changing. Call uploadFiles() amongst the stuff which already gets called by the change event handler when first photo is uploaded. Remove the 'detect' and 'type' buttons. On upload show some text which says "Automatic text detection in progress" or something like that, which then gets replaced with something like "Automatically detected text is shown below. Please check and edit if needed." I'll try and have a go at a commit.

**Comment by edent** [comment]
👍

**Comment by arizonagroovejet** [comment]
I think I've done this, but need to dig out my notes on how to do the branch commit shuffle. Also I have a question about whether I can do a commit with something I hacked in for testing commented out.

Given the bit of the code I'm messing with I looked at getting a Google Vision API key. Unless I'm missing something, the only way to get one involves giving Google credit card details. Testing a minor code contribution to someone else's project doesn't seem like the thing that makes me decide now is the time I'll give Google my credit card details having declined all their previous invitations to do so. Would you accept a commit where sendFileToCloudVision() in vision.js includes this:
```
  }).done(displayJSON);
  // uncomment the line below if you're doing testing without a Google Vision API key and want to fake successful detection of text 
  //setTimeout( function() {  displayJSON(JSON.parse('{  "responses": [  { "fullTextAnnotation": { "text": "BUFFY ANNE SUMMERS\\n1981 - 2001\\nBELOVED SISTER\\nDEVOTED FRIEND\\nSHE SAVED THE WORLD\\nA LOT" } }] }'));  }, 5000);
```
for use by other potential future people who want to contribute to this part of the code and are also not inclined to give Google their credit card info as part of doing so.

**Comment by edent** [comment]
Yes, that's fine. I think I signed up and got a bunch of free credit with Google. But I understand your reluctance. If you know of an open source OCR thing, I'll certainly consider it.

**Comment by edent** [comment]
Looks like this is buggy for images over 4MB. Complaint from user and verified by me.

Need better (any!) tests 😀

**Comment by arizonagroovejet** [comment]
I know I didn't test with an image over 4MB and I guess you didn't either before merging. :(

I think I see what's happening. The canvas element used by uploadFiles() in the event the file is larger than 4MB  is not being created before https://github.com/edent/openbenches/blob/24f83620b0e12f5c7fe9eacb1c2392fcf256bbb5/www/libs/vision/vision.js#L48 resulting in "canvas is undefined" Javascript error. Though by the time I find that error in the Firefox Console the canvas element does exist. Race condition. Maybe.

This https://github.com/edent/openbenches/blob/24f83620b0e12f5c7fe9eacb1c2392fcf256bbb5/www/add.php#L230 seems like a weird place to call uploadFiles() but presumably I thought that was a good idea at the time.

I've also noticed my commit took out the textButtons element and there's still references to it in the Javascript because obviously it didn't occur to me to grep for references other than the ones that happened to fall in front of my eyes.

*Sigh*

I vote for doing git revert or whatever to take my changes out. Maybe I'll have another go at it.
