### ISSUE TITLE
Can't select Moroccan Bench

### ISSUE THREAD

**Issue by ukmoose** [edent/openbenches#146]
If you move map to Morocco and zoom in to coast.  Try to select the bench in Essaouira, the map moves and the bench is unselected

I assume this is due to the volume of text on the bench ?

**Comment by edent** [comment]
Wow! Yup! 🤣

Guess I need to truncate that to a sensible maximum.

**Comment by summerbeth** [comment]
Thanks for flagging, now fixed.
