### ISSUE TITLE
Trying to edit bench when not logged in results in page with header logo only on some benches

### ISSUE THREAD

**Issue by ukmoose** [edent/openbenches#148]
If NOT logged in, trying to edit 
https://openbenches.org/bench/4587

Rather than being directed to twitter log in, it displays a "blank" page ( Header logo only)

**Comment by edent** [comment]
That's weird....!

4588 also fails. But 4589 works...

**Comment by edent** [comment]
Should be fixed. The long description pushed the location header beyond the 1024 byte limit.
Thanks for pointing it out :-)
