### ISSUE TITLE
Website shows wrong number of benches on some devices.

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#151]
The number of benches https://openbenches.org/ says there are differs depending on the device I'm using. E.g. 
Observed just now:

curl -s --compressed https://openbenches.org/ | grep -i "memorial benches":  5683

Firefox, Linux: Open and go to https://openbenches.org - 5668. Click Reload - 5668. Hold Shift and click Reload - 5563. Close. Open and go to https://openbenches.org - 5668. Got to https://openbenches.org/?cache=35rh35yh54h - 5683. Go to https://openbenches.org - 5668

Chrome, Linux: (maybe never seen OpenBenches before) - 5683

Safari, iOS: - Open and got to https://openbenches.org - 5664. Click Reload - 5664. Go to  https://openbenches.org/?cache=something - 5683. Go to https://openbenches.org - 5664

Observed yesterday and day before on machine I don't access to right now:
Firefox, Linux: Open and go to OpenBenches - 5500. Click Reload - 5500. Hold Shift and click Reload - Whatever number was in page as retrieved with curl at that time. Close. Open and go to OpenBenches - 5500

Given that I see the issue with Firefox on Linux on two different machines and with Safari on iOS and the number changes if I append ?cache=whatever I don't think this is a client issue. I'm wondering if the issue is caused by the "caching on the front end" you mentioned in #150, though I don't know exactly what "caching on the front end" means.

**Comment by arizonagroovejet** [comment]
Just now I opened Firefox on what I referred to above as "machine I don't access to right now" and went to https://openbenches.org and it said 5500 benches. This what Firefox sent

```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.5
Host: openbenches.org
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
```


This is what Firefox got back
```
HTTP/1.1 200 OK
accept-ranges: bytes
alt-svc: quic=":443"; ma=2592000; v="35,37,38,39"
content-encoding: gzip
content-type: text/html; charset=UTF-8
date: Sun, 22 Apr 2018 09:56:56 GMT
server: LiteSpeed
vary: Accept-Encoding
x-firefox-spdy: h2
```
As before I hit Reload and it still said 5500. So I held Shift and hit Reload and it said 5689. This is what Firefox sent
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.5
Cache-Control: no-cache
Connection: keep-alive
DNT: 1
Host: openbenches.org
Pragma: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
```
This is what Firefox got back
```
HTTP/2.0 200 OK
accept-ranges: bytes
alt-svc: quic=":443"; ma=2592000; v="35,37,38,39"
content-encoding: gzip
content-length: 3581
content-type: text/html; charset=UTF-8
date: Wed, 02 May 2018 21:00:16 GMT
server: LiteSpeed
vary: Accept-Encoding
X-Firefox-Spdy: h2
```
I then closed Firefox, opened it again, went to https://openbenches and it says 5500 again.

Safari on iOS is still behaving as described above, can't get it show any number other than 5664 without appending ?cache=something. There's no way to see the request and response.

The "Firefox, Linux" instance showing 5668 instead of 5663 is Firefox 59 on a different Fedora install. (No syncing of anything between the machines.)

Given the Firefox and Safari instances are showing different numbers of benches they're evidently not being sent the same cached version by LiteSpeed. Is it LiteSpeed saying "no newer version available than what's in your cache" unless explicitly asked to provide the latest version? To some clients, some times. 

I just looked at https://openbenches with an instance of Firefox ESR 52.7.3 on openSUSE which has looked at https://openbenches before and that's showing me 5689 benches without fiddling with the url or Shift-Reload. Whatever version of Chrome is on my Android device also shows me 5689 benches.

**Comment by ukmoose** [comment]
Seeing probably related issue with benches not appearing on the basemap.  For example https://openbenches.org/bench/5754  ( added yesterday) doesn't show up in Safari or Chrome until I physically reset the cache.  So https://openbenches.org/#51.45767/-2.595863/15 doesn't show it, then  in Chrome "reset growing data" then refresh page and new benches show up

**Comment by edent** [comment]
This seems to be a problem with the way I've configured the ServiceWorker. It's cacheing far too aggressively.

https://developers.google.com/web/ilt/pwa/caching-files-with-service-worker

**Comment by edent** [comment]
When you force refresh - or wait 24 hours - the service worker should correctly cache stuff.
