### ISSUE TITLE
When editing page, textarea for inscription may be nowhere near the photo of the text.

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#158]
On the edit page the field containing the current inscription text (if any) is displayed below whatever photos of the bench there are. The photo of the inscription is always the top photo. If there is even one photo other than the inscription text, is is impossible to have both the photo of the inscription and the field for the inscription text simultaneously visible in the same browser window on a monitor with a vertical resolution of 1200 pixels. (Many monitors have vertical resolution less than 1200 pixels.)

Moving the inscription text field so it's underneath the photo of the inscription, as it is on the add page, would make editing inscription text easier.

**Comment by edent** [comment]
Good plan! I'm planning on moving this project to Gitlab this weekend, so a pull request before then would be useful.
