### ISSUE TITLE
Bench 530 has weird longtitude

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#161]
```curl -s --compressed 'https://openbenches.org/data.json/?bench=530&format=raw' | jq
{
  "type": "FeatureCollection",
  "features": [
    {
      "id": 530,
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -7.6e-05,
          51.476151
        ]
      },
      "properties": {
        "popupContent": "Charlie Phillips<br />\r\n19.1.41-27.7.2007<br />\r\n'a wonderful family man and friend to many' …"
      }
    }
  ]
}



```

https://openbenches.org/bench/530 shows it in Greenwich London but the location string says it's in Nepal.

**Comment by arizonagroovejet** [comment]
It occurred to me this issue may be fixed by editing the bench and moving the point very very slightly. So I did that and the coordinates displayed under the map changed to something sensible. Then I saved the bench. And then I pulled the data via the API and it it looked like this

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "id": 530,
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -6.4e-05,
          51.476181
        ]
      },
      "properties": {
        "popupContent": "Charlie Phillips<br />\r\n19.1.41-27.7.2007<br />\r\n'a wonderful family man and friend to many' …"
      }
    }
  ]
}
````
which is differently bad. I tried again, this time noting the latitude and longitude that were displayed below the map, which were ```51.47618, -0.00008583069``` and now the data looks like this
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "id": 530,
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -8.6e-05,
          51.476181
        ]
      },
      "properties": {
        "popupContent": "Charlie Phillips<br />\r\n19.1.41-27.7.2007<br />\r\n'a wonderful family man and friend to many' …"
      }
    }
  ]
}
``` 
This is the only bench close enough to the prime meridian to have that many zeros in the longitude. I think the issue is in how PHP deals with numbers smaller than some value and the fix is something like
```$benchLong=sprintf('%.6f',$benchLong);```
somewhere(s).

**Comment by arizonagroovejet** [comment]
This is of course a potential problem for very small latitudes as well as very small longitudes. (I'll save some people a Google search and say the prime meridian and equator meet in the ocean.) I have no idea what to do about it. It's the use of the JSON_NUMERIC_CHECK option in the calls to json_encode e.g. https://github.com/edent/openbenches/blob/35db935f70149667318ff308a3673eb34cf4751b/www/data.json.php#L21 
that's resulting in the scientific notation. The only way not to get scientific notation I can find results in the value ending up as a string. Remove the JSON_NUMERIC_CHECK option and use sprintf  when building the arrays, e.g. 
https://github.com/edent/openbenches/blob/35db935f70149667318ff308a3673eb34cf4751b/www/mysql.php#L248
becomes
`'coordinates' => array(sprintf('%.6f',$benchLong), sprintf('%.6f',$benchLat))`
and you get e.g.
```
 "coordinates": [
"-0.000086",
"51.484859"
]
```
which I don't think is better. Someone submitted one bench really close to the prime meridian and someone else didn't realise that an 'e' indicates scientific notation, so longitude and latitude are strings now…

Maybe just add a note to the imfo about the API that very small values are in scientific notation.

**Comment by edent** [comment]
In the database, Bench 530 has:

`"latitude":"51.476181","longitude":"-0.000086"`

So it isn't being stored with that absurd precision...

**Comment by edent** [comment]
Aha! Here's the problem - a new way of handling precision.
https://stackoverflow.com/questions/42981409/php7-1-json-encode-float-issue

An easy fix incoming.

**Comment by edent** [comment]
Well, it fixes it for everything *except* bench 530 - which is obviously cursed!  I'm going to manually edit the precision in the database.
