### ISSUE TITLE
Allow easy discovery of other benches nearby.

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#162]
As I user I want to be able to easily discover other benches near the bench I'm currently looking at.

Possible implementations:

1] Provide link to a map which shows any other nearby benches.
I see a bench on Twitter, click the link and end up at https://openbenches.org/bench/8455 which shows a map with a single bench marked on it. I click a suitably prominent button/link labelled "See other benches near this one", or words to that effect, and am taken to https://openbenches.org/#51.520279/-0.153611/16  
Pros: 
- bench.php already constructs the HTML using variables for the coordinates https://github.com/edent/openbenches/blob/dd649f71da155ca1914712cdedc4bb39081ef201/www/bench.php#L60 so adding a   link like https://openbenches.org/#51.520279/-0.153611/16 would be easy.

Cons: 
- Maybe there are no other benches near this one so following the link doesn't make any other benches visible, at least not without the user zooming out. This may be potentially confusing. ("It says see other benches but doesn't show any other benches when I click it.")

2] Always show all benches.
The map on a bench page shows all benches the map, with the pointer of the bench the page is about differentiated somehow. E.g. the pointer for the bench this page is about is in red
![thisbench](https://user-images.githubusercontent.com/29510692/44364311-89f3d500-a4be-11e8-8fb9-5adb5a270216.png). 
Pros: 
- Nearby benches are discoverable without an clicking anything to make them show up.

Cons: 
- Differentiation by colour may not work for all types of colour blindness.
- I've no idea how differentiation would be done for screenreaders.
- In my observations, if a bench is very close to another bench it's pointer is not visible without clicking on a circle with a number in it, even with high zoom value. Unless there's some way around that, there would be a lot of cases where the pointer for bench wouldn't be visible on it's page without user interaction.
- Seems harder to implement than possible implementation 1.

**Comment by edent** [comment]
I like option 2.  I think a change of colour *and* a change of shape would work well.

**Comment by arizonagroovejet** [comment]
See I like option 1 because implementation is trivial enough I know I could do it, whereas I have no idea about how to do option 2 or if it would even would work for benches very close together.

**Comment by edent** [comment]
Haha! OK - write a pull request for 1 :-)

**Comment by edent** [comment]
This is now on the site. Thanks!
