### ISSUE TITLE
A bunch of curious duplicates

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#164]
Someone's submitted a bunch of duplicates today.
https://openbenches.org/bench/8257 https://openbenches.org/bench/8530
https://openbenches.org/bench/8241 https://openbenches.org/bench/8529
https://openbenches.org/bench/8256 https://openbenches.org/bench/8531
https://openbenches.org/bench/8255 https://openbenches.org/bench/8532
(there may be more, I stopped checking after four)

Given they all have the same Twitter handle on them, it seems like that person's forgotten they submitted them and then done so again. That the image urls are different in each submission suggests that they were re-submitted with different filenames, otherwise the call to duplicate_file() in add.php should have flagged the duplication and if it didn't for some reason the image urls in each submission would be the same, right?

It seems unlikely someone would re-submit a bunch of benches with the same photos but different filenames but maybe they did. I thought I'd raise an issue in part because not sure how else to point out a bunch of duplicates and in part because given the photos are identical maybe they're, at least in part, the result of something on the site not working as it should. Though the only thing I can think of is the method of storing files by checksum having changed in the last ~10 days and it doesn't look like it has, assuming the code used on the live site matches what's on GitHub.)

Perhaps check sums of the actual files could be stored and then duplicate_file() could check againts those instead. That would be slower than checking the filename, but maybe not problematically so. (My PC just did sha1 sum of a 3.6MB file in 0.011 seconds.) Or maybe that's not worth the effort as someone re-submitting the same photos of benches seems quite edge case.

**Comment by arizonagroovejet** [comment]
A lot of what I wrote above is nonsense because it is the sha1 sum of the file not the filename that's used to store the image. Even says so in the README.md

> To get around this, we calculate the SHA1 hash of each image. The image is stored in a subdirectory based on the hash

And using the filename would be silly because there'd be loads of clashes.

So the duplicates have been created using photos that look the same, at least to my eyes, but aren't.

https://openbenches.org/bench/8257 - 3840x2160, JPEG Quality 97, 4036688 bytes.
https://openbenches.org/bench/8530 - 3840x2160, JPEG Quality 87, 1636563 bytes.

It's still curious though.

**Comment by edent** [comment]
I've merged those benches. I think I might look through and see where lat/long are identical - that gets round any differences with transcribing the inscription.

**Comment by edent** [comment]
Hmmm... That won't quite work. Some different benches have identical lat/long.
https://openbenches.org/bench/3311
https://openbenches.org/bench/3318

**Comment by arizonagroovejet** [comment]
Looking at lat/long also gets around the issue of identical inscriptions on more than one bench not being an indication of a bench being duplicated. Though given the accuracy of the geotagging my phone does I, ah another comment from you just appeared as I'm typing this showing my suspicion to be correct :D

**Comment by edent** [comment]
And these two have identical inscriptions, but are different benches!
https://openbenches.org/bench/5263
https://openbenches.org/bench/5262

**Comment by arizonagroovejet** [comment]
Yep. :D https://github.com/edent/openbenches/issues/5#issuecomment-416066383
