### ISSUE TITLE
API returns truncated inscriptions

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#165]
E.g
```
$ curl --compressed -s 'https://openbenches.org/data.json/?bench=8553&format=raw'  | jq .features[].properties.popupContent
"GREATER LIVE HATH<br />\r\nNO MAN OR WOMAN<br />\r\n<br />\r\nTO THE MEMORY OF<br />\r\nCHARLES THOMAS<br />\r\nKENNEDY VC<br />\r\n<br />\r\nHIGHLAND LIGHT INFANTRY<br />\r\nBOER WAR<br />\r\n<br />\r\nBORN …"
```
compare to what's shown at https://openbenches.org/bench/8553
Truncation seems to be due to
https://github.com/edent/openbenches/blob/baa2fa5dc355b0a65c9739233ddc58b25ddbf919/www/mysql.php#L252
which is used both to get text to display on map, in which context it's reasonable to truncate, and for API where it doesn't seem reasonable to truncate.

The API section of the README doesn't mention that inscription text may be truncated.

The indiscriminate appending of … means inscriptions shown on the map always look like they've been truncated regardless of whether they have.

**Comment by arizonagroovejet** [comment]
Looks like truncation of inscriptions returned via API can also be caused by
https://github.com/edent/openbenches/blob/baa2fa5dc355b0a65c9739233ddc58b25ddbf919/www/mysql.php#L194

Is truncation of inscriptions returned via API an unintended consequence of https://github.com/edent/openbenches/commit/7ae4b1b9b6e88c2df602da3ff85b1c9bb26c6f3b  ?

Maybe get_all_benches() and get_nearest_benches() could take an argument `$truncate_inscription = false`  then
```
if ($truncate_inscription){
    $benchInscriptionReturn=nl2br(mb_substr($benchInscription,0,128) . "…");
} else {
    $benchInscriptionReturn=nl2br($benchInscription);
}
```
And later do
```
			'properties' => array(
				'popupContent' => $benchInscriptionReturn,
			),
```

Related question the answer to which may influence implementation of a fix for this issue - should inscriptions returned via the API be fed though `nl2br()` and thus contain `<br \/>` ? Is  `<br \/>`  inscriptions more likely to be useful to people getting data via the API or considered noise they strip out?  It looks like before  https://github.com/edent/openbenches/commit/7ae4b1b9b6e88c2df602da3ff85b1c9bb26c6f3b it was inconsistent whether inscriptions contained  `<br \/>`  or not depending on whether data for a single bench or all benches was requested.

**Comment by edent** [comment]
Yes, thus needs fixing. Also partly caused by #118

**Comment by arizonagroovejet** [comment]
Would you be interested in a PR for this? I reckon I could put one together for this and #166

**Comment by edent** [comment]
Ooh, yes please. I'll work on trimming the existing ones.

**Comment by arizonagroovejet** [comment]
This has turned out to be a bit more complicated than I thought because somehow it wasn't until I started poking around the code this evening that I realised inscription text to display on the map is retrieved via `data.json`. So my idea that `data.json` should always return non-truncated inscription text doesn't seem viable. I'm thinking that `data.json` needs to support an optional argument depening on whether the data is for display on the map or not. So the argument could be called `forMap`. 

I think the desirable behaviour is that `data.json` returned non-truncated transcriptions unless asked otherwise. It seems undesirable for people who have decided they want to get data to play with via `data.json`  to have to explicitly request that it doesn't truncate insciptions. So `forMap` defaults to false and calls to `data.json` from PHP scripts for the purposes of display transcriptions on the map get modified to have `&forMap=true` on the end.

If `forMap` is true then:
-  "…" is appended but only if the inscription is longer than 128 characters.
- the inscription is passed through `nl2br()` before being returned.

else
- "…" is never appended
- the inscription is not passed through `nl2br()` because the inscription containing `<br \/>` is only useful if displaying on the map. (Or on the bench page, but `bench.php` already puts the inscription retrieved via `get_bench_details()` through `nl2br()`)

Also make is so inscriptions always go through `trim()` being being returned in order to deal with known issue #166 and any future scenarios where inscriptions somehow get saved with leading or trailing whitespace.

Does that all sound sensible?

**Comment by edent** [comment]
Yes. https://openbenches.org/data.json/?bench=8553&truncated=false&format=raw Will show it without the `…`

**Comment by arizonagroovejet** [comment]
Ah, OK. I see the README does say as such. In the PR I submitted not truncating was the default and you didn't mention intention to change it so I was expecting that behaviour. Out of curiosity, why make people have to explicitly request that inscriptions are complete?
