### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by edent** [edent/openbenches#171]
A feed of latest benches.

**Comment by arizonagroovejet** [comment]
Some questions:
- How many benches should the feed contain?
- Should the XML be generated on each request, or by a cronjob every N $timeunits?
- Should the feed contain images (if so how big. should they be statically generated, what load would N RSS readers pulling X dynamically generated images every Y $timeunits create (does LiteSpeed mitigate that))?

How about something like this
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet title="XSL_formatting" type="text/xsl" href="/shared/bsp/xsl/rss/nolsol.xsl"?>
<rss  version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>OpenBenches.org</title>
    <description>An open data repository for memorial benches</description>
    <link>https://openbenches.org/</link>
    <image>
      <url>https://openbenches.org/images/icons/icon-512x512.png</url>
      <title>OpenBenches.org</title>
      <link>https://openbenches.org/</link>
    </image>
    <atom:link href="https://openbenches.org/rss" rel="self" type="application/rss+xml" />
    <lastBuildDate>Thu, 25 Oct 2018 19:30:54 GMT</lastBuildDate>
    <language>en-gb</language>
    <item>
       <title>Bench 9441</title>
       <description><![CDATA[IN LOVING MEMORY OF<br>DAISY HARRIS<br>FROM HER FAMILY<br>"ENJOY THIS VILLAGE"<br><img src="https://openbenches.org/image/d736e13fe8376eed0267e87d2b2cdcd7ae87206a/400"<br><img src="https://openbenches.org/image/9d43d0598bafce23f210922f24d22ff1ba3cf37b/400"]]></description>
       <link>https://openbenches.org/bench/9441</link>
       <guid isPermaLink="true">https://openbenches.org/bench/9441</guid>
       <pubDate>Wed, 24 Oct 2018 16:59:41 GMT</pubDate>
    </item>
  </channel>
</rss>
```
 It validates at https://validator.w3.org/feed/ It looks like this in Firefox:
![firefox](https://user-images.githubusercontent.com/29510692/47527473-81db5b80-d89a-11e8-8137-06b782b6adf8.png)

like this in FeedReder (which displays the UNIX epoch date for every item in every feed for some reason)
![feedreader](https://user-images.githubusercontent.com/29510692/47527501-90297780-d89a-11e8-90b0-0394b863cbad.png)

like this in Liferea
![liferea](https://user-images.githubusercontent.com/29510692/47527505-91f33b00-d89a-11e8-9176-6e3a4023c62c.png)

Imagine that I remembered to include the location.

I have never made an RSS feed. Possibly this is evident to people who have :smile: I cobbled the above together by hand as an experiment, I don't have code for it. But 
```select * from benches order by added desc limit 20;``` 
Iterate the results and build up the XML. Once you know what XML you want, how hard can it be… (I have never made an RSS feed) :smile:

**Comment by arizonagroovejet** [comment]
If there's a built in PHP function to generate RSS I can't find it.

**Comment by edent** [comment]
It is entirely possible that I hallucinated it...
