### ISSUE TITLE
Method for reporting issues with benches.

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#172]
As a person looking at benches, I would like an obvious and easy way to report issues. Examples:
- This bench is a duplicate. (There needs to be some mechanism to indicate the bench it's a duplicate of.)
- There is an issue with the transcribed inscription. (Someone may be unable or unwilling to edit the bench themselves. Would probably be useful if this option prompted for some info on what's wrong to save whoever acts upon the report time and effort of figuring out what is wrong, entry of which is required. E.g. "Typo, Joly instead of July".)
- This is not a memorial bench. (Sometimes people submit benches which aren't memorial benches*. Nothing prevents anyone submitting a photo of anything, so long as it's geotagged.)
- Other issue (would need to prompt for information)

Possibly list options in a drop down menu. Possibly have option to provide email address if person doing the reporting would like to be told what happened as a result.

Or maybe just put a contact email address somewhere obvious and let people email in issues.

(*) OpenBenches doesn't provide any definition of what a memorial bench is. Possibly this is a feature, not a bug. :) Though it does increase chance that if someone were to report something as not being a memorial bench, the report recipient would disagree. Or the person who submitted it would disagree and be aggrieved by it's removal. I think everyone would agree https://openbenches.org/bench/9374 is not a memorial bench because it doesn't have an inscription or show evidence it ever did. (Perhaps the add bench page should display a warning if someone tries to submit with empty inscription (where empty means no characters once all whitespace is removed)) https://openbenches.org/bench/7951 is less clear. It has an plaque and the plaque has two names. So seems plausible it's a memorial bench. But also the names on the plaque are identical to a brand of garden furniture. https://en.wikipedia.org/wiki/Smith_%26_Hawken

**Comment by edent** [comment]
That's what the comment box is for. We've had a few reports of dupes & other errors in there. 

And the ambiguity is a feature :-)

**Comment by arizonagroovejet** [comment]
Fair enough. I'd forgotten and/or not noticed that the comments had been resurrected!
