### ISSUE TITLE
Zoomed out map doesn't show correct number of pins

### ISSUE THREAD

**Issue by edent** [edent/openbenches#175]
Dramatically undercounted on zoom out.

![screenshot_2018-10-19 openbenches](https://user-images.githubusercontent.com/837136/47224599-d327ae80-d3b3-11e8-940e-fb3872d66660.png)

**Comment by edent** [comment]
See https://github.com/Leaflet/Leaflet.markercluster/issues/928

Fiddle example https://jsfiddle.net/edent/prat7wvo/13/

Seems to work on some browsers but not others?

**Comment by arizonagroovejet** [comment]
Have you seen the 8 below the orange circle with 849 in, just above Spain? If I view the zoomed out map in Safari on iOS 12, the orange circle contains 8498. Something to do with fonts maybe?

**Comment by edent** [comment]
Caused by the CSS rule `word-wrap: break-word;`
