### ISSUE TITLE
Quote marks, searching and inscription transcription

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#176]
Some inscriptions have

> "something in double straight quote marks"

E.g. https://openbenches.org/bench/1and some have
> “something in double smart quote marks”

E.g. https://openbenches.org/bench/1289

Differences in device behaviour and people's perception with regard quote marks and possibly imperfect automatic text detection, may mean people not getting relevant search results or inscriptions not being entered with the same style quotes as are in the inscription. As such I think it might be useful if when someone does a search that includes smart quotes the search also matches on straight quotes and vice versa.

In my tests, adding this
```
$quoteTranslation=array("\"" => "[\"“”]", "“" => "[\"“]", "”" => "[\"”]", "'" => "['‘’]", "‘" => "['‘]", "’" => "['’]");
$q = strtr($q,$quoteTranslation);
```
just below
https://github.com/edent/openbenches/blob/26cbeacf07b94d100ddb779b55905e56461a74c4/www/mysql.php#L669
means that a search for `“hello world”` would returns results for `"hello world"` and vice versa.

Bob sees a bench with an inscription that reads `"hello world"`. He wonders if it's on OpenBenches, takes out his Android device, searches for `"hello world"` and gets results which include the bench he's looking at. He doesn't submit the bench again.

Alice sees the same bench as Bob. She wonders if it's on OpenBenches. She takes out her iOS device. The default on iOS devices is to use smart quotes, When " (unicode `0022`) is typed, it gets automatically replaced with “ (unicode `201c`), or ” (unicode `201d`), as iOS sees fit. Alice isn't aware of this, or doesn't consider it in the moment. So although she types `"hello world"` she actually searches for `“hello world”`, gets no results and so submits the bench. Automatic detection of the inscription fails so she has to enter it manually. Due to default iOS behaviour, she enters the inscription with smart quotes as `“hello world”` Now that bench is on OpenBenches twice, but with different style quotes.

Same stories but for `'` (unicode 2022) `‘` (unicode 2018) `’` (unicode 2019).

**Comment by edent** [comment]
Good spot! Please send a PR.
