### ISSUE TITLE
Auth.com0 does not seem optional as README.md says.

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#182]
README.md says:

> **Optional** Login requires a free Auth0.com account.

(emphasis not mine). But it doesn't seem optional. In my local instance I haven't defined Auth0 stuff in `config.php` which results in
```
[11-Nov-2018 21:31:03 UTC] PHP Fatal error:  Uncaught Auth0\SDK\Exception\CoreException: Invalid domain in /var/www/html/vendor/auth0/auth0-php/src/Auth0.php:244
Stack trace:
#0 /var/www/html/functions.php(43): Auth0\SDK\Auth0->__construct(Array)
#1 /var/www/html/add.php(126): get_user_details()
#2 /var/www/html/index.php(19): include('/var/www/html/a...')
#3 {main}
```
when I access `/add/` and the page is unusable. Same happens with `/edit/`.

**Comment by edent** [comment]
Ah, it is optional for the user. Let me see if I can tweak that.
