### ISSUE TITLE
Tweet of each new bench should include @ name of uploader

### ISSUE THREAD

**Issue by maidbloke** [edent/openbenches#183]
Each new bench is tweeted from @openbenches, which is nice. If the uploader of the new bench is logged in as a Twitter user this tweet could include their @ name at the end, for example:

_In Memory of Bernard Baily
1927 - 2016
https://openbenches.org/bench/9877 
CC BY-SA 4.0
Submitted by @maidbloke_

Then Twitter will notify the submitter which might lead to more re-tweets, more views, more users, more benches...

Sadly I am not (yet) clever enough to make these changes myself.

**Comment by edent** [comment]
That's a good idea. Will have to check the length of the Twitter user's screen name, and a few other bits. But should be doable.
Might get annoying if you submit loads.

Thanks for all the benches so far :-)
