### ISSUE TITLE
Third photo gets wrong treated as panoramic.

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#184]
I thought it was weird that these two benches
https://openbenches.org/bench/9884
https://openbenches.org/bench/9885
both have photos being treated as panoramic which aren't. Once is maybe user error, twice seems suspicious. Also looks to me like someone accidentally selecting panoramic should be dealt with by 	https://github.com/edent/openbenches/blob/e3d092a50b9328c43a7ba47995dfeedac65185a0/www/functions.php#L382

I just tried adding some benches with three photos to a local instance of OpenBenches code and got photos treated as panoramic when they shouldn't be.

- Add inscription photo.
- Add second photo, leaving drop down menu on "Long shot of the bench".
- Add not panoramic third photo, leaving drop down menu on "View from the bench".
- Click "Share".

Expected result:
- Bench page shows three normal photos.

Actual result:
- Bench page shows two normal photos and third photo as panoramic.

Reproducible - 100%

Looks to me like the problem is this line
https://github.com/edent/openbenches/blob/e3d092a50b9328c43a7ba47995dfeedac65185a0/www/add.php#L294
says `media_type3` when it should say `media_type4`. I tried changing it to `media_type4` in my local copy and it fixed the problem.

The issue seems to have been introduced in https://github.com/edent/openbenches/commit/e3d092a50b9328c43a7ba47995dfeedac65185a0#diff-8b22712376eeb6bfa4531d515eff4ddf
which was on the 18th. But the most recent bench with three images other than the two mentioned above is https://openbenches.org/bench/9874 which doesn't have the problem and was posted on 20th. Was there about two days between the commit and code going live?

**Comment by edent** [comment]
Ah! I did manually correct one. That's probably why that one doesn't have the problem. Thanks for spotting.
