### ISSUE TITLE
Validate form before submit

### ISSUE THREAD

**Issue by ldodds** [edent/openbenches#28]
If you enter an inscription but forget to attach an image, then the form submits but you just end up with an empty form. Had to hit back to recover my text.

**Comment by edent** [comment]
PEBKAC WONTFIX ;-)

I need to think about the flow for adding. I'm thinking

1. Upload photo
2. Reposition if GPS isn't accurate
3. Add inscription (possibly edit OCR?)

But, for now, keeping the text and possibly adding a "don't forget the photo" message.
