### ISSUE TITLE
Ability to share link to a map view

### ISSUE THREAD

**Issue by ldodds** [edent/openbenches#29]
It would be nice to be able to share a direct link to a view of a specific area of the map

**Comment by edent** [comment]
Do you mean something more than https://openbenches.org/bench/123 ?

I guess you mean the whole dataset but zoomed into a specific location?

**Comment by ldodds** [comment]
Yep, the ability to zoom into a specific area of the dataset and share that view.

E.g. as a contributor I'd like to share a map of the benches I've just added. Or show benches in an area (e.g. in and around Bath)
