### ISSUE TITLE
Development environment / project setup instructions?

### ISSUE THREAD

**Issue by JamesMilnerUK** [edent/openbenches#32]
Hey! Awesome project :) Would love to contribute a little, unfortunately it's been a while since I've setup a PHP environment. Do you have any light instructions on how to do that? 

I'm working on the assumption that this is a standard LAMP stack project? Are there some other things I need to do to get the local development environment working? Thanks!

**Comment by edent** [comment]
Dev environment? Just edit on the live site 🤣😂

A standard PHP7 installation should be fine. It isn't using any funky extensions. 

You'll need a MySQL database - the structure can be found in the database folder. 

Add the login details to config.php

Thay *should* be sufficient. I'm away from my main computer until Sunday - but I'll do my best to answer any questions you may have.

**Comment by edent** [comment]
I've added details to the README. Shout if you need any help.

**Comment by JamesMilnerUK** [comment]
Thanks @edent . I'll look into helping out when I have a little more free time. The new logo looks great by the way!
