### ISSUE TITLE
Allow users to give the URL of an image on Wikimedia Commons

### ISSUE THREAD

**Issue by pigsonthewing** [edent/openbenches#37]
When an open-licensed image of a bench is available on Wikimedia Commons, it makes sense to allow a user to give its URL, instead of having to download, then upload, the image.

You can fetch the image yourself, using WC's API, or simply use WC as a host and display images from there.

**Comment by edent** [comment]
Good plan!

Sketch notes:

Here's an example bench - https://commons.wikimedia.org/wiki/File:AH_Green_bench_jeh.jpg

The image has geolocation metadata, and an acceptable licence.

Wikipedia API doesn't tell us much https://commons.wikimedia.org/w/api.php?action=query&titles=File:AH_Green_bench_jeh.jpg&prop=imageinfo

Commons API call is https://tools.wmflabs.org/magnus-toolserver/commonsapi.php?image=AH_Green_bench_jeh.jpg

To get EXIF as well, use https://tools.wmflabs.org/magnus-toolserver/commonsapi.php?image=AH_Green_bench_jeh.jpg&meta

Only responds in XML :-(

Need to know what all the licences are - currently gives a short name, but no list of all options.
```
<licenses><license><name>CC-Zero</name></license></licenses>
```

**Comment by pigsonthewing** [comment]
OpenPlaques may have some reusable code for this.

**Comment by edent** [comment]
Applicable licences seem to be

* Creative Commons Attribution ShareAlike 4.0 (legal code)
* Creative Commons Attribution ShareAlike 3.0 (legal code)
* Creative Commons Attribution 4.0 (legal code)
* Creative Commons Attribution 3.0 (legal code)
* Creative Commons CC0 Waiver (release all rights, like public domain: legal code)

Need to see how they're represented in the API though.

**Comment by pigsonthewing** [comment]
There may be other licences on Commons; but no image can be on Commons if it doesn't have a licence allowing free reuse (i.e. either an open licence or PD/ copyright expired).

See also https://commons.wikimedia.org/wiki/Commons:Licensing

**Comment by edent** [comment]
@pigsonthewing yup - but I need to make sure that I record (and display) the correct licence.

I don't want to label something as CC BY-SA when it's really PD.

**Comment by edent** [comment]
Within `<licenses><license><name>???</name></license></licenses>` we can have

* `CC-BY-SA-4.0`
* `CC-BY-SA-3.0`
* `CC-BY-4.0`
* `CC-BY-3.0`
* `CC-Zero`

Also has others, like

* `CC-BY-SA-2.5`
* `CC-BY-2.0`
* `CC-PD-Mark`

But they seem less common.
