### ISSUE TITLE
Add "random bench" button

### ISSUE THREAD

**Issue by pigsonthewing** [edent/openbenches#40]
Add a "Show me a random bench" button, because serendipity is cool.

**Comment by edent** [comment]
Todo

1. MySQL script to select a random row - make sure it is published.
2. Where to place the button?

**Comment by mrwilson** [comment]
This is a cool project :)

We can grab the number of benches from `get_bench_count()` - how about having a button generate a random number between 0 and that on-click with JS and then causing a page navigation? This avoids a DB hit.

```php
function randomBench() {
   var max = <?php echo get_bench_count(); ?>;
   window.location.href = 'https://www.openbenches.org/bench/' + Math.floor(Math.random()*max);
}
```

It feels like it should go next to 'Add bench' and 'Show benches near me' on the front-page.

**Comment by edent** [comment]
@mrwilson thanks :-)

It's a good suggestions - but there's a small problem. When a bench is deleted, the primary key isn't recycled. So if you delete bench `123`, then no other bench can have that ID.

I like the idea of the placement of the button though.
