### ISSUE TITLE
Search by name (suggestion)

### ISSUE THREAD

**Issue by annwitbrock** [edent/openbenches#59]
It could be hard to find a bench for a particular person, especially in a popular bench area, or if you don't know the location well.
A name search (close matches) could help people find their loved one's memorial.

**Comment by edent** [comment]
We've got a regular search - https://openbenches.org/search/?search=Jonathan

Is that what you mean?

**Comment by annwitbrock** [comment]
Ah, I didn't see it. It might be better located above the map.
