### ISSUE TITLE
Panorama view from bench (suggestion)

### ISSUE THREAD

**Issue by annwitbrock** [edent/openbenches#60]
This is a bit of a stretch, but a panorama view from the bench might make a nice virtually being there experience. As someone who has browsed online cemetery photos curiously looking for headstones of ancestors abroad, I think this could be a nice feature.

**Comment by edent** [comment]
This should now work.

* Panorama https://openbenches.org/bench/879
* Photosphere https://openbenches.org/bench/868

**Comment by annwitbrock** [comment]
Looks good.
