### ISSUE TITLE
Inscription format

### ISSUE THREAD

**Issue by dougaitken** [edent/openbenches#69]
As a contributor, I want to understand what is "correct" inscription format.

* Line by line same as bench
* Full caps, all lower

**Comment by edent** [comment]
We've left this quite loose for now. Some people type it in as seen, others correct capitalisation, linebreaks are inconsistent.

What do you think the standard should be - and how should we inform people?

**Comment by dougaitken** [comment]
Ideally having the content to match the inscription on the bench, however, the way things are is good. 

Inform people - possibly an example bench? Or placeholder text showing formatting? 

Saying that, most I've seen are in all caps, but on the web that looks odd to me so I've capitalised the first letter of each word.

**Comment by edent** [comment]
OK. @summerbeth please add some `placeholder` text to the inscription box. Showing a multi line, sample inscription, in sentence case.
