### ISSUE TITLE
Return raw json

### ISSUE THREAD

**Issue by fiskurgit** [edent/openbenches#72]
Possibly by supplying a ?format=rawjson query param. 

Geojson.php currently returns the json prefixed with `var benches =` for use in the web frontend, it'd be helpful for other implementations if it was possible to return the data without this JS field prefix and just return the raw json: `{...}`

**Comment by edent** [comment]
You can get all the data, or partial data, from the API.  Data is returned in [geoJSON](http://geojson.org/) format.

* All Data
	* `https://openbenches.org/data.json/`
* Specific Bench
	* `https://openbenches.org/data.json/?bench=123`
	* That last `/` is *required*.
* Geographic Area (Haversine)
	* `https://openbenches.org/data.json/?latitude=51.234&longitude=-1.234&radius=20`
	* `latitude` and `longitude` in [WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System).
	* `radius` in Kilometres.
	* A maximum of 20 results are returned.
	* That last `/` is *required*.
* Formats
	* By default, the JSON starts with `var benches = `
	* To get pure JSON, append `format=raw`
	* `https://openbenches.org/data.json/?bench=123&format=raw`
* Images
	* The API doesn't return images. Yet.
