### ISSUE TITLE
Categorise Benches

### ISSUE THREAD

**Issue by edent** [edent/openbenches#91]
A curated list of "funny" benches, or other sorts of categories. For a blog?

**Comment by kjmears** [comment]
Also - by Material? Wood, Metal, that funny Black Plastic that apes Wood - could be interesting.

**Comment by edent** [comment]
@kjmears interesting idea. We've got 5,000 benches now, so it might be a bit hard to go back and do them all. Happy if you want to look into it.

**Comment by pigsonthewing** [comment]
There are lots of other potential categories, such as:

- Benches for more than one person
- Benches for dogs
- By year of death
- Benches with a poem on the plaque

Maybe allow a folksonomy to develop?

**Comment by pigsonthewing** [comment]
>  pigsonthewing unassigned summerbeth an hour ago 

Oops! Mis-click, sorry. Can't seem to re-assign.

**Comment by edent** [comment]
Working my way through http://howto.philippkeller.com/2005/04/24/Tags-Database-schemas/
