### ISSUE TITLE
Inconsistent buttons for adding new benches.

### ISSUE THREAD

**Issue by arizonagroovejet** [edent/openbenches#94]
https://openbenches.org/ has two buttons people can click to add a new bench. One button is labelled "New Bench" and the other "Add a new bench". Clicking either button takes the visitor to the same place and as such should they should have the same label. 

The buttons achieve the same thing but are implemented differently. "New Bench" is an input element which submits a form and takes the visitor to https://openbenches.org/add/  Because it's an input element it can't be right/context/long clicked to open the destination in a new tab.
"Add a new bench" is a div that contains a hyperlink to https://openbenches.org/add/ which be right/context/long clicked to open the destination in a new tab. Since both buttons do the same thing it seems logical that they be constructed identically. The hyperlink method seems preferable.

**Comment by edent** [comment]
Yup - sounds good. Go ahead and make the change. 

From memory, one is a button so it will line up with the other. Worth testing to make sure it still looks OK.

**Comment by arizonagroovejet** [comment]
Now I'm going to have to look up again how to do do this whole forking branching pull request malarky. :D

**Comment by arizonagroovejet** [comment]
Consistent wording on buttons to add benches. All the things to click look consistent.
https://validator.w3.org says "No errors or warnings to show." when fed the HTML.

![firefoxafter](https://user-images.githubusercontent.com/29510692/29994783-d05648a2-8fcf-11e7-9852-d1dd0ea62c66.png)

For comparison this is what the site currently looks like in Firefox

![firefoxbefore](https://user-images.githubusercontent.com/29510692/29994785-df888286-8fcf-11e7-99c3-967a322178c2.png)

Those weird almost drop shadow like border things don't show up in all browsers.

Look good? If so I'll try and sort out a pull request with the changes.

**Comment by edent** [comment]
Looks good. Send a PR - to a different branch - and I'll test it out.
